ruby/mspec

lib/mspec/helpers/ruby_exe.rb, spec/helpers/ruby_exe_spec.rb
There is no concrete example that `File.executable?` is not reliable on Windows.
=> Remove unreasonable code

lib/mspec/helpers/numeric.rb
It should use the MAX and MIN value of Javascript Numbers specified in:
http://www.ecma-international.org/ecma-262/6.0/#sec-number.max_safe_integer
=> Fix fixnum_max and fixnum_min for my Opal Bignum Implementation

lib/mspec/helpers/ruby_exe.rb
$() is now POSIX standard, however may not be supported on some
systems.
Fix #9
=> Do not use $() for portability

lib/mspec/utils/options.rb
When an option which has no arguments is followed by wrong option,
`process` method may return `nil` and then causes `NoMethodError`.
=> Fix exception at wrong option

lib/mspec.rb
When missing pp (like mruby), Current implementation is not readable
```rb
[:a].should == [:b]
#=> Expected #<Array:0x7fa79981f800> to equal #<Array:0x7fa79981f500>
```
Because it's calling `Kernel#inspect` instead of `Array#inspect`
I expect like this
```rb
[:a].should == [:b]
#=> Expected [:a] to equal [:b]
```
=> Lazy calling for inspect

lib/mspec/mocks/proxy.rb, spec/mocks/proxy_spec.rb
When a conversion is called on the target object which responds to `to_int`, it should be called actually and check the result.
=> `MockIntObject#to_int`

lib/mspec/utils/script.rb
`Etc.nprocessors` is portable and available on all living versions
since 2.2.
=> Use `Etc.nprocessors`

lib/mspec/commands/mspec.rb
mspec puts warnging with this message in mruby .
`'*' interpreted as argument prefix`
=> Suppress warning for mruby

.travis.yml
I notice travis isn't running MSpec's  tests on the latest backports.
=> Update travis versions.

README.md, lib/mspec/utils/script.rb
ref: https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/, https://github.com/ruby/mspec/pull/40
=> Remove Ruby 2.3 support

lib/mspec/utils/version.rb
Hi.
I'm using mspec on mruby.
mruby's `Integer()` does not call `to_int`.
see also https://github.com/mruby/mruby/commit/afca99a40b8a3415b3a9a0e8fc41c93ddcbb11d8
=> Call `to_int` explicitly for mruby

lib/mspec/utils/script.rb
I use `mspec` for `backports`.
I use it to run recent specs against old rubies that have had features backported.
I am in the process of using `ruby/mspec` instead of `mspec` gem because some specs no longer run (in particular because `lambda?` helper is new, not sure if there are other reasons).
So that the specs run, I need to tell `ruby_version_is` what the actual target is. There used to be `SpecGuard.ruby_version_override=`, which as been removed. I can go around that.
Also, `mspec` refuses to run older Rubies .. This PR is a small change to allow me to run `mspec` from older versions by turning an error into a warning / or overwrite the method altogether.
I imagine that the minimum Ruby requirement is constantly being bumped to minimize support. I'm not sure it is the right …
=> Allow older rubies (with warning)

tool/remove_old_guards.rb
This makes `tool/remove_old_guards.rb` also delete comments like the ones in ruby/spec#915
=> Also remove comments immediately preceding old guards

tool/check_require_spec_helper.rb
Adds a script that can be used to check that `require_relative` for spec_helper is in each *_spec.rb file.  Having the require in each file is helpful so each spec can be easily run standalone with ruby from the command line. 
This is in response to https://github.com/ruby/spec/pull/992 per @eregon 's request.
Note that this is a simple check for "require_relative .*spec_helper" in each *_spec.rb file and it would incorrectly fail the case where a *_spec.rb file required another file which required spec_helper.
=> Add script to check require_relative for spec_helper

lib/mspec/runner/mspec.rb
suppress https://github.com/ruby/ruby/security/code-scanning/792 warning.
=> Use File.readlines instead of IO.readlines

lib/mspec/runner/actions/leakchecker.rb
The leakchecker will report leaked file descriptors when tests do things like access `Etc.getgrgid`, for example, if NSS modules (like `sss`) handle these lookups by connecting to a daemon like `sssd` and leave the connection open.
To address this, we can call glibc's `__nss_configure_lookup` to override NSS modules configured in /etc/nsswitch.conf and only use ordinary file/DNS lookups.
This should fix the rubyci.org failures on Amazon Linux like this one: http://rubyci.s3.amazonaws.com/amazon2023/ruby-master/log/20240119T003005Z.log.html.gz#rubyspec
=> Disable NSS modules when using the leakchecker

lib/mspec/runner/actions/leakchecker.rb
I thought this was a part of glibc, but it's not - it's actually a part of systemd-hostnamed. We definitely don't want this, because it's 1) not guaranteed to be on all systems, and 2) will make a dbus connection which is exactly what we don't want.
=> Don't load myhostname NSS module in leakchecker

lib/mspec/runner/actions/leakchecker.rb
The fiddle gem has changed more than I thought! We can't depend on CONST_STRING being available, nor the Fiddle::Type module. Thankfully, passing strings _in_ as VOIDP or CONST_STRING works the same, and we don't need to look at any string results, so we can just use the old/new types interchangeably.
=> Don't depend on Fiddle features which aren't in Ruby 3.0

lib/mspec/mocks/mock.rb, spec/mocks/mock_spec.rb
As discussed in https://github.com/ruby/mspec/issues/67.
The commits are incremental and coherent changes, so going commit by commit may be the easiest way to review.
`rspec` on this repo, and the `mspec` on ruby-spec are both passing with these changes.
To see the impact easily, edit `ruby-spec/spec/core/hash/compare_by_identity_spec.rb` to only leave the spec `uses #equal? semantics, but doesn't actually call #equal? to determine identity`. (line 50)
Then run `../mspec/bin/mspec --repeat 1000000 core/hash/compare_by_identity_spec.rb`.
It should be easy to see the memory that just keeps going up quickly (before this change) using `top` or similar monitoring tool.
=> Fix memory leak in mock

lib/mspec/helpers/tmp.rb
Ref: https://github.com/ruby/ruby/pull/10235
As discussed upstream, the mutability is only used in one spec, `path.rb`:
```ruby
@name = +"file_to_path"
@path = tmp(@name)
```
For all the others it doesn't matter if the argument is mutated or not.
cc @eregon
=> tmp: accept frozen strings

lib/mspec/commands/mkspec.rb, lib/mspec/commands/mspec-ci.rb, lib/mspec/commands/mspec-run.rb, lib/mspec/commands/mspec-tag.rb, lib/mspec/commands/mspec.rb
This file has probably been moved at some point, the old version would to `lib/mspec/lib` which does not exist. The new version is inspired by the syntax of `bin/mspec-run` to keep things consistent.
Since the usual way to call this script is via `bin/mspec-run`, and that sets up your load path, an alternative way to fix this would be to simply remove this load path update in this file.
=> Update load path modification in mspec-run.rb

tool/remove_old_guards.rb
Changes:
- make the script executable
- add naive validation of parameters
- add an example into the documentation comment
=> Polish the tool/remove_old_guards.rb script

lib/mspec/commands/mspec-ci.rb, spec/commands/mspec_ci_spec.rb, spec/commands/mspec_run_spec.rb
The repeat option was only supported by the run command, but for convenience this adds it to the ci command. Specs are also added to ensure the option is available for both commands.
Fixes #74
=> Add repeat option to ci command
